export const CREATE_USER = 'CREATE_USER'
export const READ_USERS = 'READ_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const FILTER_USERS = 'FILTER_USERS'
export const SEARCH_USER = 'SEARCH_USER'